parameters:
  twitter.consumer_key: '%env(TWITTER_CONSUMER_KEY)%'
  twitter.consumer_secret: '%env(TWITTER_CONSUMER_SECRET)%'
  twitter.access_token: '%env(TWITTER_ACCESS_TOKEN)%'
  twitter.access_token_secret: '%env(TWITTER_ACCESS_TOKEN_SECRET)%'
